C
C     DATOS COMUNES PARA TODAS LAS RUTINAS
C     DEL SOLVENTE (SISTEMA CLASICO)
C
      module hibrido_common
      include 'param'
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER (NAT=nt)
      PARAMETER (ZERO=0.0)
      PARAMETER (ONE=1.D0)
      PARAMETER (TWO=2.D0)
      PARAMETER (THREE=3.D0)
      PARAMETER (FOUR=4.D0)
      PARAMETER (FIVE=5.D0)
      PARAMETER (PTFIVE=0.5D0)
      PARAMETER (THIRD3=1.D0/3.D0)
      PARAMETER (PI=3.14159265358979312D0)
      PARAMETER (FPI=4.D0*PI)
      PARAMETER (TWOPI=2.D0*PI)
      PARAMETER (EE=4.80324 D02)
      PARAMETER (AVNUM=6.022045 D23)
      PARAMETER (BOLTZF=1.380662 D0)
      PARAMETER (A0=0.52918 D0)
      PARAMETER (HH=EE*EE/A0)

      CHARACTER*5, dimension (:), allocatable :: AT
      CHARACTER*5 CR

c     NT
      real*8, dimension(:), allocatable :: X,Y,Z,X0,Y0,Z0,VX,
     > VY,VZ,VX0,VY0,VZ0,XX,YY,ZZ,EPOL,EC,FX,FY,FZ,GX,GY,GZ,
     > GQ,X1,Y1,Z1,XX1,YY1,ZZ1,PC0,PC,PCC,FQ,VQ0,VQ,FQC,FQP,
     > FQV,EAC,rrcu,rrcuq,FQQ,PC1
      
c     NTQSS
      real*8, dimension(:), allocatable :: DELVF,FFF,EPS,SIGMA,WWM,E12,
     > F12,E6,F6,AZ,ZZZ,DA,TEMPA,VF

      real*8 ST,S0,SD,SD0,QS,GDF,GDFSLV,GDFSLT,GDQ,KMAX,NDGREE
      integer, dimension(:), allocatable :: NNAT

c     NT
      integer, dimension(:), allocatable :: JNFC
      integer IS0,IS0Q,IEWLD,ITEL,NTIME,NSCAL,NWAT,NPART,NSPECQ
      integer IPR1,IP15,NCX,NCY,NCZ,NEWV,NEWQ,IPR,IMPR,ICMOT,IQMOT,IFLUC
      integer KG(8,1100),IGRIL,IGGRID,NDFT,NPAS,ICON,NSAVE,IRDF,NEW,IZZ
      integer IRAS,NWATC,IDUM,NATOM,KSQMAX
      integer UMBRE,US1,US2,US3,US4,NQ      

      real*8 AC(500),LT(100),TEMPOL,FACTOR
      real*8 REDEL,DELTAT
      real*8 FACTA,FACTV,FACT2,TEMPRQ,TEMPRQQ,TOTMASQ
      real*8 WWQ,VFQ,RCT,RCTSQ,RKAPPA,RKAPPA2
      real*8 TEMPAV,TEMTRS,TEPION,RRNIT,RM2
      real*8 BXLGTH,CC,ETLR,VTLR,RHO,E2,TEMPSLV,TEMPSLT
      real*8 VCT,VLJ,VCOO,VOO,VOH,VHH,VTOT,VLJQC,VCQC
      real*8 TOTMAS,WEIGHT            
      real*8 TOLL,VINC,MAXI5,MAXIT,TEMPS
      real*8 NEIGH(30,30),COSANG,FL1,FL2,DOH      
      real*8 SUMF,SUMFX,SUMFY,SUMFZ
      real*8 DIX(51,101),DIY(51,101),DIZ(51,101),PIP(51,101)
      real*8 QA,QB,AXI,BYI,CZI
      real*8 DELR,ENEFUR,GGRID,GRIL
      real*8 AB,B,CB,UC,FC,AF,BF,CSHIFT,ESHIFT,RBUF,DELR2      
      real*8 VSELF,OV(10),ENOH,EGP,ECSELF
      real*8 STQ,S0Q,SDQ,SD0Q,QSQ,FFQ,AA,BB,DD      
      real*8 DIPT,XFAX,NANG,IUNID,CONVF,CCQ,ICLSTR
      real*8 KG1(2,101,101),QK(101,101)
      real*8 VCSS(NAT),VCSSO,VCSSH,VCSST,Xmi(3,3)
      real*8 X99,CKUM,RUM,KBER,BER1,BER2,BERSTEP,JVEL
      real*8 EE12O,EE12H,EE6O,EE6H
      real*8 FF12O,FF12H,FF6O,FF6H
      real*8 FF12OH,FF6OH,EE12OH,EE6OH
      real*8 ALFA1,ALFA2
      real*8 TEMPRSV
      real*8 ELFIELD,D
      endmodule
