#!/bin/env ruby
matchear=ARGV.first
i = 1

while (s = STDIN.gets)
  if (matchear == 'NCOvsM' || matchear == 'e')
    r = s[/ #{matchear}: -?(\d+(\.\d+)?)/,1] or next
    puts "#{i} #{r.to_f}" unless r.nil?
  else
    if (s !~ /#{matchear}: ((\d+)s. )?(\d+)us/) then next end
    segundos = $2.to_i + ($3.to_f / 1000000)
    puts "#{i} #{segundos}"
  end
  
  i = i+1
end
