#!/bin/env ruby
matchear=ARGV.first
i = 1

while (s = STDIN.gets)
  if (matchear == 'NCOvsM' || matchear == 'e')
    r = s[/ #{matchear}: -?(\d+(\.\d+)?)/,1] or next
    puts "#{i} #{r.to_f}" unless r.nil?
  else
    segundos = s[/#{matchear}: (\d+)us/,1] or next
    puts "#{i} #{segundos.to_f / 1000000}"
  end
  
  i = i+1
end
