#!/usr/bin/ruby

Dir.chdir('agua1')

File.open('gpu_options','w') {|io| io.puts \
"max_function_exponent 8
little_cube_size 11.0
min_points_per_cube 1"
}

puts 'Corriendo GPU...'
gpu_output = `../../garcha/garcha-gpu < t`[/SCF ENERGY\s+=\s+(-?\d+\.\d+)/,1].to_f
puts 'Corriendo CPU...'
cpu_output = `../../garcha/garcha-cpu < t`[/SCF ENERGY\s+=\s+(-?\d+\.\d+)/,1].to_f
delta = ((gpu_output - cpu_output) * 627.5).abs
delta_ref = 0.00100951948859063

puts "Energia GPU: #{gpu_output}"
puts "Energia CPU: #{cpu_output}"
puts "Delta: #{delta} : #{delta <= delta_ref ? 'OK' : 'PROBLEMA!'}"
puts "Referencia: #{delta_ref}"


