#!/bin/env ruby
require 'fileutils'
StepRange = Struct.new(:range,:step)

class Combination < Hash
  def save(file)
    File.open(file,'w') do |f|
      self.map {|k,v| f.puts "#{k} #{v}"}
    end
  end

  def to_s
    self.map {|k,v| "#{k} = #{v}"}.join('; ') + "\n"
  end
end

if (ARGV.first.nil?)
  STDERR.puts "usage: #{$0} <dir> [.. <dir>]"
  exit(1)
end

VERBOSE=ARGV.include?('-v')
USE_EXISTING_OPTIONS=ARGV.include?('-existing')
SAVE_BEST=ARGV.include?('-save')
USE_BEST_RECALC=ARGV.include?('-best-recalc')
USE_BEST_STORE=ARGV.include?('-best-store')
USE_BEST_CPU=ARGV.include?('-best-cpu')

def variation(ranges, combination = Combination.new, block = Proc.new)
  if (ranges.empty?) then block.call(combination.dup)
  else
    ranges = ranges.dup
    var,values = ranges.shift

    if (values.is_a?(StepRange))
      values.range.step(values.step) do |v|
        combination[var] = v
        variation(ranges, combination, block)
      end
    else
      combination[var] = values
      variation(ranges, combination, block)
    end
  end
end

def run_gpu
  if (VERBOSE)
    system('/usr/bin/time -a -o /dev/stdout -f "real %e\nuser %U\nsys %S\nswaps %F" ../../fortran/garcha-g2g < t')
  else
    # run
    output = `/usr/bin/time -a -o /dev/stdout -f "real %e\nuser %U\nsys %S\nswaps %F" ../../fortran/garcha-g2g < t`
    if ($? != 0) then raise 'Execution failed!' end

    # analyze
    results = {
      :e => output[/SCF ENERGY\s+=\s+(-?\d+\.\d+)/,1],
      :time => output[/real (\d+\.\d+)/,1],
      :dim => output[/prism size (\(\d+,\d+,\d+\))/,1],
      :pts_tot => output[/Grilla original: (\d+)/,1],
      :funcs_tot => output[/Grilla original: \d+ puntos, (\d+)/,1],
      :pts => output[/Grilla final: (\d+)/,1],
      :funcs => output[/Grilla final: \d+ puntos, (\d+)/,1],
      :iteration => output[/iteration: ((\d+s\. )?\d+us\.)/,1],
      :density => output[/TIMER: density\/energy ((\d+s\. )?\d+us\.)/,1],
      :rmm => output[/TIMER: rmm: ((\d+s\. )?\d+us\.)/,1],
      :NCOxM => output[/NCOxM: (\d+)/,1],
      :MxM => output[/MxM: (\d+)/,1],
      :NCOvsM =>  output[/NCOxM: (\d+)/,1].to_f / output[/MxM: (\d+)/,1].to_f,
      :impl => output[/Kernels: (gpu|cpu)/,1],
      :swaps => output[/swaps (\d+)/,1],
      :mem_used => output[/Maximum used memory: (\d+(\.\d+)?MB)/,1],
      :mem_perc => output[/Maximum used memory: \S+ \((\d+(\.\d+)?%)\)/,1],
    }
    results.map {|k,v| print "#{k}: #{v.nil? ? '-' : v} "}; puts

    return results
  end
end

begin
  ranges = {
    :little_cube_size => StepRange.new((4.5..13),0.5),
    :max_function_exponent => StepRange.new((12..12),1),
    :min_points_per_cube => StepRange.new((1..1),1),
    :sphere_radius => StepRange.new((0.3..0.8),0.1)
#    :assign_all_functions => 1
  }

  dirs = ARGV.reject {|arg| arg =~ /^-/}
  dirs.each do |dir|
    Dir.chdir(dir)
    puts "=> #{dir}"

    if (USE_EXISTING_OPTIONS)
      if (USE_BEST_RECALC) then FileUtils.cp('gpu_options.recalc.best', 'gpu_options'); puts 'Using best recalc' end
      if (USE_BEST_STORE) then FileUtils.cp('gpu_options.store.best', 'gpu_options'); puts 'Using best store' end
      if (USE_BEST_CPU) then FileUtils.cp('gpu_options.cpu.best', 'gpu_options'); puts 'Using best cpu' end
      run_gpu()
    else
      best_combination = nil
      best_results = nil
      lowest_time = Float::MAX

      variation(ranges) do |combination|
        combination.save('gpu_options')
        puts combination
        results = run_gpu()

        if (results[:swaps].to_i > 0) then raise 'Swaps detected!' end

        current_time = results[:iteration]
        current_time = current_time[/(\d+)s./,1].to_i + (current_time[/(\d+)us./,1].to_f / 1000000)
        if (current_time < lowest_time)
          lowest_time = current_time
          best_combination = combination
          best_results = results
        end
      end

      FileUtils.rm('gpu_options', :force => true)

      if (SAVE_BEST && !best_combination.nil?) then
        best_combination.save("gpu_options.#{best_results[:impl]}.best")
        puts 'BEST COMBINATION:',best_combination,"BEST TIME: #{lowest_time}s"
      end
    end

    Dir.chdir('..')
  end
end
