#!/usr/bin/ruby
VERBOSE=false
USE_EXISTING_OPTIONS=true

require 'fileutils'
StepRange = Struct.new(:range,:step)

if (ARGV.first.nil?)
  STDERR.puts "usage: #{$0} <dir> [.. <dir>]"
  exit(1)
end

def variation(ranges, combination = {}, block = Proc.new)
  if (ranges.empty?) then block.call(combination)
  else
    ranges = ranges.dup
    var,values = ranges.shift
    
    if (values.is_a?(StepRange)) 
      values.range.step(values.step) do |v|
        combination[var] = v
        variation(ranges, combination, block)
      end
    else
      combination[var] = values
      variation(ranges, combination, block)
    end
  end
end

def run_gpu
  if (VERBOSE)
    system('/usr/bin/time -p -a -o /dev/stdout ../../garcha/garcha-gpu < t')
  else
    # run
    output = `/usr/bin/time -p -a -o /dev/stdout ../../garcha/garcha-gpu < t`
    
    # analyze
    results = {
      :e => output[/SCF ENERGY\s+=\s+(-?\d+\.\d+)/,1],
      :time => output[/real (\d+\.\d+)/,1],
      :dim => output[/prism size (\(\d+,\d+,\d+\))/,1],
      :pts_tot => output[/Grilla original: (\d+)/,1],
      :funcs_tot => output[/Grilla original: \d+ puntos, (\d+)/,1],          
      :pts => output[/Grilla final: (\d+)/,1],
      :funcs => output[/Grilla final: \d+ puntos, (\d+)/,1],
      :first_solve => output[/gpu_solve_cubes ((\d+s\. )?\d+us\.)/,1],
      :density => output[/TIMER: density\/energy ((\d+s\. )?\d+us\.)/,1],
      :rmm => output[/TIMER: rmm: ((\d+s\. )?\d+us\.)/,1]          
    }
    results.map {|k,v| print "#{k}: #{v.nil? ? '-' : v} "}; puts
  end
end

begin
  ranges = {
    :little_cube_size => StepRange.new((11.5..30.5),0.5),
    :max_function_exponent => StepRange.new((8..8),2),
    :min_points_per_cube => StepRange.new((1..1),1),
    :sphere_radius => StepRange.new((0.0..0.6),0.6)
#    :assign_all_functions => 1
  }

  ARGV.each do |dir|
    Dir.chdir(dir)
    puts "=> #{dir}"
  
    if (USE_EXISTING_OPTIONS)
      run_gpu()
    else
      variation(ranges) do |combination|
        File.open('gpu_options','w') do |f|
          combination.each_pair {|k,v| print "#{k} = #{v}; "}; puts
          combination.map {|k,v| f.puts "#{k} #{v}"}
        end
        
        run_gpu()
      end
    
      FileUtils.rm('gpu_options', :force => true)
    end
    
    Dir.chdir('..')      
  end
end
