# -*- mode: make -*-
CXXFLAGS:=$(CXXFLAGS) $(EXTRA_FLAGS) -Wall -Wno-long-long -ansi -Wno-unused

%.o:%.cpp %.h
	$(CXX) $(CXXFLAGS) -c $< -o $@
  
%.o:%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@
  
%.o:%.c %.h
	$(CC) $(CFLAGS) -c $< -o $@
