# -*- mode: make -*-
CXXFLAGS:=$(CXXFLAGS) $(EXTRA_FLAGS) -Wall -Wno-long-long -ansi

%.o:%.cpp %.h
	g++ $(CXXFLAGS) -c $< -o $@
  
%.o:%.cpp
	g++ $(CXXFLAGS) -c $< -o $@
  
%.o:%.c %.h
	gcc $(CFLAGS) -c $< -o $@
