#! /bin/bash


for i in {2..15..1}
 
do
  echo  little_cube_size $i max_function_exponent 10 min_points_per_cube 1 sphere_radius 0.5 > gpu_options
  /home/nano/garcha2-gpu/fortran/garcha-g2g < t | grep exchfock > tiempos$i

  echo  little_cube_size $i.5 max_function_exponent 10 min_points_per_cube 1 sphere_radius 0.5 > gpu_options
  /home/nano/garcha2-gpu/fortran/garcha-g2g < t | grep exchfock > tiempos$i.5
done
./corrervim
./a.out

