#-*- mode: make -*-

OBJ =      int.o init.o drive.o SCF.o  func.o     \
           int2.o  int3.o int3G.o exch.o    \
           exch2.o pot.o int2G.o int1G.o \
           geom.o intSG.o MD2.o write.o \
           dns.o dns2.o dnsg.o potg.o dip.o dipG.o  \
           int3N.o exchnum.o exchnum2.o grid.o\
           densg.o  exchfock.o\
           nwrite.o dfp2.o lsearch.o SCFop.o\
           densgop.o dns2op.o dnsop.o exchnum2op.o\
           exchnumop.o potop.o alg.o eig.o svd.o \
           dnsgop.o potgop.o elec.o charge.o dip2.o vol.o\
            mmsol.o mmsolG.o intsolG.o intsol.o resp.o\
            efield.o lalg.o popu.o int3mem.o int3lu.o
#COMPFLG =  -march=athlon-xp -O3 -pipe -fomit-frame-pointer -c\
           -falign-loops=2 -fno-strength-reduce \
           -ffast-math  -falign-functions=2
COMPFLG  = -mp1 -ip -O3 -c
COMPFLG2 = -O     -c
#more or less general
LINKFLG = -lm -static-libcxa 
CPPFLAGS =  -P -traditional-cpp
DEFINE   = -Dpack
LIBS= -L/opt/intel/mkl/9.0/lib/em64t -lmkl_lapack64 -lmkl_em64t -lguide

all: big

clean:
	rm -f *.o big

big :  $(OBJ)
	ifort -o big $(OBJ) $(LINKFLG) $(LIBS)
  
init.o    : init.f
	ifort $(COMPFLG) init.f 
int.o    : int.f param
	ifort $(COMPFLG) int.f 
int1G.o    : int1G.f param
	ifort $(COMPFLG2) int1G.f 
drive.o : drive.f param 
	ifort $(COMPFLG2) drive.f 
func.o : func.f
	ifort $(COMPFLG) func.f 
int2.o    : int2.f param
	ifort -cpp $(DEFINE) $(COMPFLG) int2.f 
int2G.o    : int2G.f param
	ifort $(COMPFLG) int2G.f 
int3G.o    : int3G.f param
	ifort $(COMPFLG2) int3G.f 
int3.o    : int3.f param
	ifort -cpp $(DEFINE) $(COMPFLG2) int3.f
int3N.o    : int3N.f param
	ifort -cpp $(DEFINE) $(COMPFLG2) int3N.f
int3lu.o    : int3lu.f param
	ifort -cpp $(DEFINE) $(COMPFLG2) int3lu.f
int3mem.o    : int3mem.f param
	ifort $(COMPFLG2) int3mem.f
exch.o    : exch.f param
	ifort -cpp $(DEFINE) $(COMPFLG) exch.f
exch2.o    : exch2.f param
	ifort -cpp $(DEFINE) $(COMPFLG) exch2.f
pot.o    : pot.f 
	ifort $(COMPFLG) pot.f 
SCF.o    : SCF.f param
	ifort -cpp $(DEFINE) $(COMPFLG) SCF.f
MD2.o     : MD2.f param
	ifort $(COMPFLG) MD2.f 
geom.o     : geom.f param
	ifort -cpp $(DEFINE) $(COMPFLG) geom.f
intSG.o     : intSG.f param
	ifort $(COMPFLG) intSG.f 
dfp2.o     : dfp2.f param
	ifort $(COMPFLG) dfp2.f 
lsearch.o     : lsearch.f param
	ifort $(COMPFLG) lsearch.f 
write.o     : write.f param
	ifort -cpp $(DEFINE) $(COMPFLG) write.f
nwrite.o     : nwrite.f param
	ifort -cpp $(DEFINE) $(COMPFLG) nwrite.f
dns.o     : dns.f param
	ifort $(COMPFLG) dns.f 
dns2.o     : dns2.f param
	ifort $(COMPFLG) dns2.f 
dnsg.o     : dnsg.f param
	ifort $(COMPFLG) dnsg.f 
densg.o     : densg.f param
	ifort $(COMPFLG) densg.f 
potg.o     : potg.f 
	ifort $(COMPFLG) potg.f 
dip.o     : dip.f param
	ifort $(COMPFLG) dip.f 
dipG.o     : dipG.f param
	ifort $(COMPFLG) dipG.f 
dip2.o     : dip2.f param
	ifort $(COMPFLG) dip2.f 
vol.o     : vol.f param
	ifort $(COMPFLG) vol.f 
exchnum.o     : exchnum.f param
	ifort $(COMPFLG) exchnum.f 
grid.o     : grid.f
	ifort $(COMPFLG) grid.f 
exchnum2.o     : exchnum2.f param
	ifort $(COMPFLG) exchnum2.f 
exchfock.o     : exchfock.f param
	ifort $(COMPFLG) exchfock.f 
SCFop.o    : SCFop.f param
	ifort -cpp $(DEFINE) $(COMPFLG) SCFop.f
densgop.o     : densgop.f param
	ifort $(COMPFLG) densgop.f
dns2op.o     : dns2op.f param
	ifort $(COMPFLG) dns2op.f
dnsop.o     : dnsop.f param
	ifort $(COMPFLG) dnsop.f
exchnum2op.o     : exchnum2op.f param
	ifort $(COMPFLG) exchnum2op.f
exchnumop.o     : exchnumop.f param
	ifort $(COMPFLG) exchnumop.f
potop.o     : potop.f param
	ifort $(COMPFLG) potop.f
potgop.o     : potgop.f 
	ifort $(COMPFLG) potgop.f
dnsgop.o     : dnsgop.f param
	ifort $(COMPFLG) dnsgop.f
alg.o     : alg.f 
	ifort $(COMPFLG) alg.f
eig.o     : eig.f
	ifort $(COMPFLG2) eig.f
svd.o     : svd.f
	ifort $(COMPFLG) svd.f
elec.o     : elec.f param
	ifort $(COMPFLG) elec.f 
charge.o   : charge.f param
	ifort -cpp $(DEFINE) $(COMPFLG) charge.f
intsol.o    : intsol.f param
	ifort $(COMPFLG) intsol.f 
mmsol.o    : mmsol.f param
	ifort $(COMPFLG) mmsol.f 
intsolG.o    : intsolG.f param
	ifort $(COMPFLG2) intsolG.f 
mmsolG.o    : mmsolG.f param
	ifort $(COMPFLG) mmsolG.f 
resp.o    : resp.f param
	ifort $(COMPFLG) resp.f 
efield.o    : efield.f param
	ifort $(COMPFLG) efield.f 
lalg.o    : lalg.f param
	ifort $(COMPFLG) lalg.f 
popu.o    : popu.f param
	ifort $(COMPFLG) popu.f 




