
ifeq ($(libint),1)
    LIBS_LIBINT = -L/$(LIBINT_HOME)/lib -lint2
    INCS_LIBINT = -I/$(LIBINT_HOME)/include -I/$(LIBINT_HOME)/include/libint2 -I/$(EIGEN_HOME)
    LIBRARIES  += $(LIBS_LIBINT)
    CXXFLAGS   += -std=c++11 $(INCS_LIBINT)

    SRCS       += libint/libintproxy.cpp
    OBJ        += libint/libintproxy.o
endif
