# EXTERNALS
vpath 
# accumulate_point.o: calc_ggaCS.h calc_ggaOS.h calc_ldaCS.h
cpu/iteration.o : pointxc/calc_ggaCS.h pointxc/calc_ggaOS.h pointxc/calc_ldaCS.h
cuda/iteration.o: pointxc/calc_ggaCS.h pointxc/calc_ggaOS.h pointxc/calc_ldaCS.h

# INTERNALS
#calc_ggaCS.h: pbeCS.h
#calc_ggaOS.h: pbeOS_main.h
#pbeOS_main.h: pbeOS_corr.h pbeOS_exch.h
#pbeOS_corr.h: gcorc.h
#pbeCS.h: gcorc.h

