# DO NOT DELETE

classify_functions.o: common.h init.h matrix.h cpu/cpu_vector_types.h
classify_functions.o: cuda_includes.h cuda/cuda_extra.h scalar_vector_types.h
classify_functions.o: datatypes/cpu_primitives.h partition.h timer.h
classify_functions.o: global_memory_pool.h
global_memory_pool.o: global_memory_pool.h cuda/cuda_extra.h cuda_includes.h
init.o: common.h cuda_includes.h cuda/cuda_extra.h init.h matrix.h
init.o: cpu/cpu_vector_types.h scalar_vector_types.h
init.o: datatypes/cpu_primitives.h timer.h partition.h global_memory_pool.h
IntegralCache.o: IntegralCache.h
matrix.o: common.h matrix.h cpu/cpu_vector_types.h cuda_includes.h
matrix.o: cuda/cuda_extra.h scalar_vector_types.h datatypes/cpu_primitives.h
partition.o: common.h init.h matrix.h cpu/cpu_vector_types.h cuda_includes.h
partition.o: cuda/cuda_extra.h scalar_vector_types.h
partition.o: datatypes/cpu_primitives.h partition.h timer.h
partition.o: global_memory_pool.h
regenerate_partition.o: common.h init.h matrix.h cpu/cpu_vector_types.h
regenerate_partition.o: cuda_includes.h cuda/cuda_extra.h
regenerate_partition.o: scalar_vector_types.h datatypes/cpu_primitives.h
regenerate_partition.o: partition.h timer.h global_memory_pool.h
timer.o: timer.h cuda_includes.h cuda/cuda_extra.h
cuda/iteration.cu_o: common.h init.h matrix.h cpu/cpu_vector_types.h
cuda/iteration.cu_o: cuda_includes.h cuda/cuda_extra.h scalar_vector_types.h
cuda/iteration.cu_o: datatypes/cpu_primitives.h cuda/cuda_extra.h matrix.h
cuda/iteration.cu_o: timer.h partition.h timer.h global_memory_pool.h
cuda/iteration.cu_o: scalar_vector_types.h global_memory_pool.h
cuda/iteration.cu_o: cuda/gpu_variables.h cuda/kernels/pot.h
cuda/iteration.cu_o: cuda/kernels/pot_open.h cuda/kernels/accumulate_point.h
cuda/iteration.cu_o: cuda/kernels/energy.h cuda/kernels/energy_open.h
cuda/iteration.cu_o: cuda/kernels/energy_derivs.h cuda/kernels/rmm.h
cuda/iteration.cu_o: cuda/kernels/weight.h cuda/kernels/functions.h
cuda/iteration.cu_o: cuda/kernels/force.h cuda/kernels/transpose.h
cuda/iteration.cu_o: cuda/kernels/qmmm_forces.h cuda/kernels/qmmm_energy.h cuda/kernels/qmmm_terms/forces/ss.h
cuda/iteration.cu_o: cuda/kernels/qmmm_terms/forces/ps_unrolled.h cuda/kernels/qmmm_terms/forces/pp_unrolled.h
cuda/iteration.cu_o: cuda/kernels/qmmm_terms/forces/ds_unrolled.h cuda/kernels/qmmm_terms/forces/dp_unrolled.h
cuda/iteration.cu_o: cuda/kernels/qmmm_terms/forces/dd_unrolled.h
cuda/iteration.cu_o: cuda/kernels/qmmm_terms/energy/ss.h
cuda/iteration.cu_o: cuda/kernels/qmmm_terms/energy/ps.h cuda/kernels/qmmm_terms/energy/pp.h
cuda/iteration.cu_o: cuda/kernels/qmmm_terms/energy/ds.h cuda/kernels/qmmm_terms/energy/dp_unrolled.h
cuda/iteration.cu_o: cuda/kernels/qmmm_terms/energy/dd_unrolled.h
cuda/iteration.cu_o: cuda/kernels/coulomb_forces.h
cuda/iteration.cu_o: cuda/kernels/coulomb_terms/forces/ss_s.h cuda/kernels/coulomb_terms/forces/ps_s.h
cuda/iteration.cu_o: cuda/kernels/coulomb_terms/forces/pp_s.h cuda/kernels/coulomb_terms/forces/ds_s.h
cuda/iteration.cu_o: cuda/kernels/coulomb_terms/forces/dp_s.h cuda/kernels/coulomb_terms/forces/dd_s.h
cuda/iteration.cu_o: cuda/kernels/coulomb_terms/forces/ss_p.h cuda/kernels/coulomb_terms/forces/ps_p.h
cuda/iteration.cu_o: cuda/kernels/coulomb_terms/forces/pp_p.h cuda/kernels/coulomb_terms/forces/ds_p.h
cuda/iteration.cu_o: cuda/kernels/coulomb_terms/forces/dp_p.h cuda/kernels/coulomb_terms/forces/dd_p.h
cuda/iteration.cu_o: cuda/kernels/coulomb_terms/forces/ss_d.h cuda/kernels/coulomb_terms/forces/ps_d.h
cuda/iteration.cu_o: cuda/kernels/coulomb_terms/forces/pp_d.h cuda/kernels/coulomb_terms/forces/ds_d.h
cuda/iteration.cu_o: cuda/kernels/coulomb_terms/forces/dp_d.h cuda/kernels/coulomb_terms/forces/dd_d.h
