
SRCS += excited/saverho.cpp 
OBJ  += excited/saverho.o

SRCS += excited/g2g_calculate2e.cpp
OBJ  += excited/g2g_calculate2e.o

SRCS += excited/g2g_calculateXC.cpp
OBJ  += excited/g2g_calculateXC.o

SRCS += excited/g2g_calculateG.cpp
OBJ  += excited/g2g_calculateG.o

SRCS += excited/calc_coef.cpp
OBJ  += excited/calc_coef.o
