#!/bin/bash
rm -f libg2g-*.so 
make clean all sm20=1 full_double=0 time=1 $* 
mv libg2g.so libg2g-gpu-f.so
make clean all sm20=1 full_double=1 time=1 $*
mv libg2g.so libg2g-gpu-d.so
make clean all cpu=1 full_double=0 time=1 $*
mv libg2g.so libg2g-cpu-f.so
make clean all cpu=1 full_double=1 time=1 $*
mv libg2g.so libg2g-cpu-d.so
