# -*- mode: make -*-

CUDA_SOURCES=$(wildcard *.cu)
CUDA_HEADERS=$(wildcard *.h)
include Makefile.cuda

all: $(CUDA_OBJ)

clean:
	rm -f *.cu_o *.cudafe* *.ptx *.hash *.cubin *.i *.ii *.fatbin.* *.cu.c



