liosolo:
	ifort -o tdanalyze tdanalyze.f90
	ifort -o tdanalize1 tdanalize1.f90
	ifort -o tdanalize2 tdanalize2.f90
	ifort -o tdanalyze-splitpropagation tdanalyze-splitpropagation.f90
clean:
	rm -rf tdanalize1
	rm -rf tdanalize2
	rm -rf tdanalyze
	rm -rf tdanalyze-splitpropagation
