# Function to print build configuration information
function(print_yes_no VAR)
  if(${VAR})
    message(STATUS "  ${VAR}: YES")
  else()
    message(STATUS "  ${VAR}: NO")
  endif()
endfunction()

# Print build configuration
message(STATUS "")
message(STATUS "LIO Build Configuration:")
message(STATUS "=======================")
message(STATUS "Version: ${LIO_VERSION}")
message(STATUS "Git Hash: ${GIT_HASH}")
message(STATUS "")

message(STATUS "Compiler Information:")
message(STATUS "  C Compiler: ${CMAKE_C_COMPILER}")
message(STATUS "  C++ Compiler: ${CMAKE_CXX_COMPILER}")
message(STATUS "  Fortran Compiler: ${CMAKE_Fortran_COMPILER}")
if(USE_CUDA)
  message(STATUS "  CUDA Compiler: ${CMAKE_CUDA_COMPILER}")
  message(STATUS "  CUDA Architectures: ${CMAKE_CUDA_ARCHITECHTURES}")
endif()

message(STATUS "")
message(STATUS "Build Options:")
print_yes_no(USE_CUDA)
print_yes_no(USE_INTEL_COMPILER)
print_yes_no(USE_MKL)
print_yes_no(USE_PARALLEL)
print_yes_no(USE_FULL_DOUBLE)
print_yes_no(AINT_MP)
print_yes_no(USE_LIBXC_CPU)
print_yes_no(USE_LIBXC_GPU)
print_yes_no(USE_LIBINT) 
print_yes_no(USE_CUBLAS)
print_yes_no(USE_MAGMA)
print_yes_no(USE_DFTD3)
print_yes_no(USE_PROFILING)
print_yes_no(USE_DEBUGGING)
print_yes_no(USE_FULL_CHECKS)
print_yes_no(BUILD_TESTING)
print_yes_no(USE_ANALYTICS)
print_yes_no(CUDA_USE_FAST_MATH)
print_yes_no(CUDA_VERBOSE)
print_yes_no(CUDA_PTX)
print_yes_no(CUDA_REGCOUNT)
print_yes_no(CPU_RECOMPUTE)


message(STATUS "")
message(STATUS "Installation Paths:")
message(STATUS "  Install prefix: ${CMAKE_INSTALL_PREFIX}")
message(STATUS "  Libraries: ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}")
message(STATUS "  Binaries: ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR}")
message(STATUS "  Data: ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_DATADIR}/lio/dat")
message(STATUS "")