# This action runs a linter in the codebase.
#
# From https://github.com/github/super-linter, it 
name: Lint Code Base

on:
  pull_request:
    branches: [master, develop]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Disable copy detection among files since it is very noisy in fortran.
          VALIDATE_JSCPD: false
          # Remove these lines once the CPP and Python are clang-format and pep8 compliant.
          VALIDATE_CPP: false
          VALIDATE_PYTHON: false 
